config/routes.rb
Rails.application.routes.draw do
  get "/project", to: 'pages#project'
  get "/contact" , to: 'pages#contact'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
   root "pages#home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def project
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Desafio Proyecto Nuevo" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>


<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Portafolio</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to 'Home', root_path, class:'nav-link active', "aria-current": "page" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Project', project_path, class:'nav-link active', "aria-current": "page" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Contact', contact_path, class:'nav-link active', "aria-current": "page" %>
        </li>
        </li>
      </ul>
    </div>
  </div>
</nav>


<body class="container center"> 
    <%= yield %>
</body>

  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>

</html>

app/views/pages/contact.html.erb
<h1 class="my-5 text-center">Contactame</h1>

<div class="card">
  <h5 class="card-header">Desarrollador</h5>
  <div class="card-body">
    <h5 class="card-title">Buscanos en mis redes sociales</h5>
    <p class="card-text">"Soy un desarrollador web apasionado con una habilidad innata para transformar ideas en soluciones digitales innovadoras y funcionales. Mi compromiso con la excelencia y la satisfacción del cliente me distingue, garantizando resultados que superan expectativas. Trabajo con dedicación y creatividad para llevar cada proyecto a su máximo potencial."</p>
    <a href="#" class="btn btn-primary boton">📲  Contactame</a>
  </div>
</div>

app/views/pages/home.html.erb
<h1 class="my-5 text-center">Portafolio</h1>

<p>Un portafolio de proyectos de desarrolladores web es una colección digital que exhibe trabajos y habilidades de un profesional en el área. Incluye ejemplos de sitios web creados, aplicaciones web desarrolladas y otras iniciativas digitales. Este portafolio demuestra la capacidad del desarrollador para abordar diversos desafíos técnicos y creativos, mostrando su experiencia y estilo único. Sirve como una herramienta esencial para atraer a potenciales clientes y empleadores, permitiéndoles evaluar la calidad del trabajo y la adaptabilidad del desarrollador a diferentes proyectos y necesidades específicas. Es, en esencia, una carta de presentación profesional en formato digital.</p>

app/views/pages/project.html.erb
<h1 class="my-5 text-center">Proyectos Realizados</h1>

<div class="card mb-3" style="max-width: 540px50%;">
  <div class="row g-0">
    <div class="col-md-4">
      <%= image_tag 'martin.png', class: "img-fluid rounded-start max-width: 100% " %>
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h5 class="card-title">Mi Primera pagina web</h5>
        <p class="card-text">Este es el primer proyecto realizado en html el cual consiste en realizar una pagina werb como curriculum vitae de algun personaje a eleccion.</p>
        <p class="card-text"><small class="text-body-secondary">Martin Lutero</p>
      </div>
    </div>
  </div>
</div>

<br>

<div class="card mb-3" style="max-width: 540px50%;">
  <div class="row g-0">
    <div class="col-md-4">
      <%= image_tag 'suricata.png', class: "img-fluid rounded-start max-width: 100% " %>
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h5 class="card-title">Suricata - pagina web</h5>
        <p class="card-text">Este es el primer proyecto realizado en html el cual consiste en realizar una pagina werb como curriculum vitae de algun personaje a eleccion.</p>
        <p class="card-text"><small class="text-body-secondary">Martin Lutero</p>
      </div>
    </div>
  </div>
</div>

<br>


<div class="card mb-3" style="max-width: 540px50%;">
  <div class="row g-0">
    <div class="col-md-4">
      <%= image_tag 'cuppon.png', class: "img-fluid rounded-start max-width: 100% " %>
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h5 class="card-title">Cuppon - pagina web</h5>
        <p class="card-text">Este es el primer proyecto realizado en html el cual consiste en realizar una pagina werb como curriculum vitae de algun personaje a eleccion.</p>
        <p class="card-text"><small class="text-body-secondary">Martin Lutero</p>
      </div>
    </div>
  </div>
</div>

<br> 

<div class="position-relative top-50 start-50">
<button type="button" class="btn btn-primary middle boton">Ver Más</button>
</div>